const list ={
   
    Telepath:{
        tittle:"Telepath",
        textColor: "rgb(252, 255, 61)",
        back:"index.html",
        fondo:"/Images/telepath.jpg",
        letra:"Don't even finish that sentence, babe\nAlready know how this ends\nYou say: We're breaking up\nWhat a shame\nDon't even wanna stay friends, God\n\nIt's just so you\nYou're just so predictable\nWon't you try something original?\nOld news, reused\nThat's why I don't cry\n\n'Cause I gotta feelin'\nYou're coming back\nJust like you have in the past\nYeah, I gotta feelin'\nYou'll be sending me trash\nYou shoulda left in the drafts\n\nYeah, I gotta feelin'\nYou'll see me movin' on\nAnd hate that I'm gone\nI can see it\nYou're comin' back\nCall me a telepath\n\nNow's about the time the boredom hits (oh, look)\nThere you are at my door\nDrunk and asking me for a kiss\nWhen yesterday you said that you hate my guts\nNow you're back in love?\n\nIt's so you\nYou're just so predictable\nWon't you try something original?\nOld news, reused\nThat's why I don't cry\n\n'Cause I gotta feelin'\nYou're coming back\nJust like you have in the past\nYeah, I gotta feelin'\nYou'll be sending me trash\nYou shoulda left in the drafts\n\nYeah, I gotta feelin'\nYou'll see me movin' on\nAnd hate that I'm gone\nI can see it\nYou're comin' back\nCall me a telepath\n\nBut, I betcha, I betcha, I betcha, I betcha\nI'll call you when I'm cryin', yeah\nI betcha, I betcha, I betcha, I betcha\nYou'll return in perfect timing\nAnd I won't stop you from tryin'\n\n'Cause I gotta feelin'\nYou're coming back\nJust like you have in the past\nYeah, I gotta feelin'\nYou'll be sending me trash\nYou shoulda left in the drafts\n\nYeah, I gotta feelin'\nYou'll see me movin' on\nAnd hate that I'm gone\nI can see it\nYou're comin' back\nCall me a telepath\n\nCall me a telepath, woah\nCall me a telepath\nCall me a telepath, oh\nCall me a telepath",
        traduccion:"Ni siquiera acabes esa oración, bebé\nYa sé cómo termina\nDirás que terminamos\nQué pena\nNi siquiera quieres seguir siendo amigos, Dios\n\nEs tan tú\nEres tan predecible\n¿No probarás algo original?\nViejas noticias, reutilizadas\nPor eso no lloro\n\nPorque tengo el presentimiento\nQue regresarás\nComo hiciste en el pasado\nSí, tengo el presentimiento\nQue me enviarás basura\nQue debiste dejar en tus borradores\n\nSí, tengo el presentimiento\nQue me verás superándote\nY odiarás que me haya ido\nPuedo verlo\nVas a volver\nLlámame telépata\n\nYa es hora que te alcance el aburrimiento (oh, mira)\nAhí estás frente a mi puerta\nBorracho y pidiéndome un beso\nCuando ayer dijiste que me odias a morir\n¿Ahora me amas otra vez?\n\nEs tan tú\nEres tan predecible\n¿No probarás algo original?\nViejas noticias, reutilizadas\nPor eso no lloro\n\nPorque tengo el presentimiento\nQue regresaras\nComo hiciste en el pasado\nSí, tengo el presentimiento\nMe enviarás basura\nQue debiste haber dejado en borradores\n\nSí, tengo el presentimiento\nQue me verás superándote\nY odiarás que me haya ido\nPuedo verlo\nVas a volver\nLlámame telépata\n\nPero te apuesto, te apuesto, te apuesto, te apuesto\nQue te llamaré cuando llore, sí\nTe apuesto, te apuesto, te apuesto, te apuesto\nY volverás en el momento oportuno\nY no te detendré\n\nPorque tengo el presentimiento\nQue regresarás\nComo hiciste en el pasado\nSí, tengo el presentimiento\nMe enviarás basura\nQue debiste haber dejado en borradores\n\nSí, tengo el presentimiento\nQue me verás superándote\nY odiarás que me haya ido\nPuedo verlo\nVas a volver\nLlámame telépata\n\nLlámame telepata, woah\nLlámame telepata\nLlámame telepata, oh\nLlámame telepata",
        video:"https://www.youtube.com/embed/6kiYXT8frBo?si=2GGll7Ssyv49sXDg",
        reproductor:"/Audios/Telepath.mp3"
    },
    IdleTown:{
        tittle:"Idle Town",
        back:"Songs.html?album=Sunsetseason",
        textColor: "rgb(245, 106, 81)",
        fondo:"/Images/SunsetSeason.jpg",
        letra:"This town will never change\nPeople come and go, it's all the same\nSpeed the roads on our doubting days\nTo any place that's far away\n\nI never learned anybody's name\nWe all vowed that we wouldn't stay\nKissing signs on the interstate\nAll we do for now is sit and wait\n\nIn our idle town, in our idle town\n\nYeah, we invent our own little games\nWhen the lights out at the stadium, hey\nMaking life a spinning arcade\nAnd curfew's at midnight, we watch the sunrise\nWe watch the sunrise\nWe watch the Sun\n\nSpringtime when the air is thin\nWe're getting antsy and they're noticing\nWhile everybody's off partying\nWe're watching stars over ice-cream\n\nAnd now we're kicking up to seventh gear\nAnd we're breathing in the atmosphere\nAnd I don't even need a sip of beer\nYeah I can feel it all\n\nIn our idle town, in our idle town\n\nYeah, we invent our own little games\nWhen the lights out at the stadium, hey\nMaking life a spinning arcade\nAnd curfew's at midnight, we watch the sunrise\nWe watch the sunrise\nWe watch the Sun\n\nAnd they watched the sunrise\nBlinking out of red eyes, and sore minds\nThe airplanes keep flying by, and they cry\n'Cause they've never even touched the sky\nNo, they'll never even touch the sky\n\nYeah we invent our own little games\nAnd everybody's trying to escape\nKilling time at the yellow café\nAnd curfew's at midnight\n\nYeah I think that we'll all be okay\nThe idle town will stay as it stays\nAnd everyone I love's in this place\nSo curfew's at midnight\nWe watch the sunrise",
        traduccion:"Esta ciudad nunca cambiará\nLa gente va y viene, es todo lo mismo\nAcelerar las carreteras en nuestros días de duda\nA cualquier lugar que esté lejos\n\nNunca aprendí el nombre de nadie\nTodos juramos que no nos quedaríamos\nLas señales de besos en la interestatal\nTodo lo que hacemos por ahora es sentarnos y esperar\n\nEn nuestro pueblo ocioso, en nuestro pueblo ocioso\n\nSí, inventamos nuestros propios jueguitos\nCuando las luces del estadio se apagan, hey\nHaciendo de la vida una arcada giratoria\nY el toque de queda es a medianoche, vemos el amanecer\nVemos el amanecer\nMiramos el Sol\n\nLa primavera, cuando el aire es fino\nNos estamos poniendo ansiosos y ellos están notando\nMientras todo el mundo está fuera de fiesta\nEstamos viendo las estrellas sobre el helado\n\nY ahora estamos pasando a la séptima velocidad\nY estamos respirando la atmósfera\nY ni siquiera necesito un sorbo de cerveza\nSí, puedo sentirlo todo\n\nEn nuestro pueblo ocioso, en nuestro pueblo ocioso\n\nSí, inventamos nuestros propios jueguitos\nCuando las luces del estadio se apagan, hey\nHaciendo de la vida una arcada giratoria\nY el toque de queda es a medianoche, vemos el amanecer\nVemos el amanecer\nMiramos el Sol\n\nY vieron el amanecer\nParpadear con los ojos rojos, y las mentes doloridas\nLos aviones siguen volando, y lloran\nPorque nunca han tocado el cielo\nNo, ni siquiera tocarán el cielo\n\nSí, inventamos nuestros propios jueguitos\nY todo el mundo está tratando de escapar\nMatar el tiempo en el café amarillo\nY el toque de queda es a medianoche\n\nSí, creo que todos estaremos bien\nEl pueblo ocioso se quedará como se queda\nY todos los que amo están en este lugar\nAsí que el toque de queda es a medianoche\nVemos el amanecer",
        video:"https://www.youtube.com/embed/BI5_hpUxDrM?si=m_Tk3-jIMy_KfFTD",
        reproductor:"/Audios/IdleTown.mp3"
    },
    GenerationWhy:{
        tittle:"Generation Why",
        back:"Songs.html?album=Sunsetseason",
        textColor: "rgb(245, 106, 81)",
        fondo:"/Images/SunsetSeason.jpg",
        letra:"Why, why, why, why\nWhy, why, why, why\nWhy, why, why\n\nI was off\nKeying cars parked on radium lawns\nBy suburbian moms\nI called a friend\nLet's meet at ten\nGo wherever we want\n'Cause no one cares that we're gone\n\nThis town don't got much to do\nYou and I haven't got much to lose\nSo do you wanna rot in your room like we always do?\nTalk about how fast we grew\nAnd all the big dreams that we won't pursue\nThen get in your car and laugh till we both turn blue\n\n'Cause we are the helpless, selfish, one of a kind\nMillennium kids, that all wanna die\nWalking in the street with no light inside our eyes\n(Why)\nWe are the worthless, cursed with too much time\nWe get into trouble and lose our minds\nSomething that I've heard a million times in my life\nGeneration Why\n\nParents think, we're fast asleep\nBut as soon as we're home, we're sneaking out the window\n'Cause at this rate of earth decay\nOur world's ending at noon\nCan we all just move to the Moon?\n\nThis town don't got much to do\nAnd you and I haven't got much to lose\nSo do you wanna leave everyone in this place for good?\n\n'Cause we are the helpless, selfish, one of a kind\nMillennium kids, that all wanna die\nWalking in the street with no light inside our eyes\nWe are the worthless, cursed with too much time\nWe get into trouble and lose our minds\nSomething that I've heard a million times in my life\nGeneration Why\n\nWhy, why, why, why, why, why, why, why\nWe're livin' night to night\nWhy, why, why, why, why, why, why, why\nSince we're bound to die, oh\nWhy, why, why, why, why, why, why, why\nOh, what's the use in trying?\nWhy, why, why, why, why, why, why, why\nAnd it's exactly why\n\n'Cause we are the helpless, selfish, one of a kind\nMillennium kids, that all wanna die\nWalking in the street with no light inside our eyes\nWe are the worthless, cursed with too much time\nWe get into trouble and lose our minds\nSomething that I've heard a million times in my life\nGeneration why\n\nWhy, why, why, why, why, why, why, why?\nWhy, why, why, why, why, why, why, why?\nWhy, why, why, why, why, why, why, why?\nWhy, why, why, why, why, why, why, why?",
        traduccion:"Por qué, por qué, por qué\nPor qué, por qué, por qué\nPor qué, por qué\n\nYo estaba fuera\nLlave de coches aparcados en el césped del radio\nPor las madres de los suburbios\nLlamé a un amigo\nQuedamos a las diez\nIr a donde queramos\nPorque a nadie le importa que nos hayamos ido\n\nEste pueblo no tiene mucho que hacer\nTú y yo no tenemos mucho que perder\nEntonces, ¿quieres rockear en tu habitación como siempre lo hacemos?\nHabla de lo rápido que crecimos\nY todos los grandes sueños que no perseguimos\nEntonces sube a tu coche y ríete hasta que los dos nos pongamos azules\n\nPorque somos los indefensos, egoístas, únicos en su clase\nLos niños del milenio, que todos quieren morir\nCaminar en la calle sin luz dentro de nuestros ojos\n(Por qué)\nSomos los inútiles, malditos con demasiado tiempo\nNos metemos en problemas y perdemos la cabeza\nAlgo que he escuchado un millón de veces en mi vida\nGeneración Por qué\n\nLos padres piensan que estamos dormidos\nPero tan pronto como estamos en casa, nos escabullimos por la ventana\nPorque a este ritmo de decadencia de la Tierra\nNuestro mundo se acaba al mediodía\n¿Podemos irnos todos a la Luna?\n\nEste pueblo no tiene mucho que hacer\nY tú y yo no tenemos mucho que perder\n¿Así que quieres dejar a todos en este lugar para siempre?\n\nPorque somos los indefensos, egoístas, únicos en su clase\nLos niños del milenio, que todos quieren morir\nCaminar en la calle sin luz dentro de nuestros ojos\nSomos los inútiles, malditos con demasiado tiempo\nNos metemos en problemas y perdemos la cabeza\nAlgo que he escuchado un millón de veces en mi vida\nGeneración Por qué\n\nPor qué, por qué, por qué, por qué, por qué, por qué, por qué\nEstamos viviendo noche a noche\nPor qué, por qué, por qué, por qué, por qué, por qué, por qué\nYa que estamos destinados a morir, oh\nPor qué, por qué, por qué, por qué, por qué, por qué, por qué\n¿De qué sirve intentarlo?\nPor qué, por qué, por qué, por qué, por qué, por qué, por qué\nY es exactamente por qué\n\nPorque somos los indefensos, egoístas, unímos\nNiños del Milenio, que todos quieren morir\nCaminando por la calle sin luz dentro de nuestros ojos\nSomos los inútiles, maldecidos con demasiado tiempo\nNos metimos en problemas y perdemos la cabeza\nAlgo que he oído un millón de veces en mi vida\nGeneración por qué\n\n¿Por qué, por qué, por qué, por qué, por qué, por qué, por qué?\n¿Por qué, por qué, por qué, por qué, por qué, por qué, por qué?\n¿Por qué, por qué, por qué, por qué, por qué, por qué, por qué?\n¿Por qué, por qué, por qué, por qué, por qué, por qué, por qué?",
        video:"https://www.youtube.com/embed/entVpj_IT6M?si=oSoaLTWEtQsidQvZ",
        reproductor:"/Audios/genwhy.mp3"
    },
    CrushCulture:{
        tittle:"Crush Culture",
        back:"Songs.html?album=Sunsetseason",
        textColor: "rgb(245, 106, 81)",
        fondo:"/Images/SunsetSeason.jpg",
        letra:"(Crush culture)\n\nMy God, don't look at your phone\nNo one's gonna call you\nQuit checking your volume\n(Crush)\n\nI don't care if I'm forever alone\nI'm not falling for you\n'Cause this baby is loveproof\n(Culture)\n\nI don't care what you're saying\nI don't wanna participate\nIn your game of manipulation\n(Crush)\n\nAnd no, I don't want your sympathy\nAll this love is suffocating\nJust let me be sad and lonely\n'Cause\n\nCrush culture makes me\nWanna spill my guts out\nI know what you're doing\nTryna get me to pursue you\n\nCrush culture makes me\nWanna spill my guts out\nSpill my guts out\nSpill my guts out\n\nOh no, don't look in their eyes\n'Cause that's how they get you\nKiss you then forget you\n(Crush)\n\nAll they feed in you is beautiful lies\nSo hide in the bathroom\nTill they find someone else new\n(Culture)\n\nI don't care what you're saying\nI don't wanna participate\nIn your game of manipulation\n(Crush)\n\nAnd no I don't want your sympathy\nAll this love is suffocating\nJust let me be sad and lonely\n'Cause\n\nCrush culture makes me\nWanna spill my guts out\nI know what you're doing\nTryna get me to pursue you\n\nCrush culture makes me\nWanna spill my guts out\nSpill my guts out\nSpill my guts out\n\nShut your damn mouth\nYou're talking too loud\nAnd no one cares if you two made out\nI'm sick of the kissing cult\n\nCrush culture makes me\nWanna spill my guts out\nI know what you're doing\nTryna get me to pursue you\n\nCrush culture makes me\nWanna spill my guts out\nSpill my guts out\nSpill my guts out\n\nCrush culture makes me\nWanna spill my guts out\nI know what you're doing\nTryna get me to pursue you\n\nCrush culture makes me\nWanna spill my guts out\nSpill my guts out\nSpill my guts out",
        traduccion:"(Cultura del enamoramiento)\n\nDíos mío, no revises tu teléfono\nNadie te va a llamar\nDeja de revisar el volumen\n(Enamoramiento)\n\nNo me importa estar solo para siempre\nNo voy a enamorarme de ti\nPorque este chico es inmune al amor\n(Cultura)\n\nNo me importa lo que dices\nNo quiero participar\nEn tu juego de manipulación\n(Enamoramiento)\n\nY no, no quiero tu lástima\nTodo este amor es sofocante\nSolo déjame estar triste y solo\nPorque\n\nLa cultura del enamoramiento me hace\nQuerer vomitar mis entrañas\nSé lo que estás haciendo\nTratando de hacer que te persiga\n\nLa cultura del enamoramiento me hace\nQuerer vomitar mis entrañas\nVomitar mis entrañas\nVomitar mis entrañas\n\nOh no, no le mires a los ojos\nPorque así es como te atrapan\nTe besan, luego te olvidan\n(Enamoramiento)\n\nSolo te alimentan de hermosas mentiras\nAsí que escóndete en el baño\nHasta que encuentren a alguien nuevo\n(Cultura)\n\nNo me importa lo que dices\nNo quiero participar\nEn tu juego de manipulación\n(Enamoramiento)\n\nY no, no quiero tu lástima\nTodo este amor es sofocante\nSolo déjame estar triste y solo\nPorque\n\nLa cultura del enamoramiento me hace\nQuerer vomitar mis entrañas\nSé lo que estás haciendo\nTratando de hacer que te persiga\n\nLa cultura del enamoramiento me hace\nQuerer vomitar mis entrañas\nVomitar mis entrañas\nVomitar mis entrañas\n\nCierra tu maldita boca\nHablas demasiado alto\nY a nadie le importa si lo hicieron\nEstoy harto del culto de los besos\n\nLa cultura del enamoramiento me hace\nQuerer vomitar mis entrañas\nSé lo que estás haciendo\nTratando de hacer que te persiga\n\nLa cultura del enamoramiento me hace\nQuerer vomitar mis entrañas\nVomitar mis entrañas\nVomitar mis entrañas\n\nLa cultura del enamoramiento me hace\nQuerer vomitar mis entrañas\nSé lo que estás haciendo\nTratando de hacer que te persiga\n\nLa cultura del enamoramiento me hace\nQuerer vomitar mis entrañas\nVomitar mis entrañas\nVomitar mis entrañas",
        video:"https://www.youtube.com/embed/GzYSzV7Mltc?si=ty86dvevDr1l_0Qw",
        reproductor:"/Audios/CrushCulture.mp3"
    },
    GreekGod:{
        tittle:"Greek God",
        textColor: "rgb(245, 106, 81)",
        back:"Songs.html?album=Sunsetseason",
        fondo:"/Images/SunsetSeason.jpg",
        letra:"Oh, I don't really care if you like me or not\nBut I know that you want me to\nOh, anythin' I do, I know you're gonna watch\nTo rumor up that I'm a fool\nYou and all your friends have to walk in a squad\n'Cause y'all are so insecure\nOh, overcompensate 'cause you're sizin' me up\nThe oldest trick in the book\n\nThere's nothin' you could do\nTo dampen up my mood\nThere's nothing you could say\nWon't like you anyways\nI know that you've been hurt\nDon't mean that it's our turn\nMmm\n\n'Cause I know what you really want\nA little more confidence\nThis is where it's gotta stop\nI'm tired of hearin' it\nYou're just gonna be a fraud\nOh, with nothin' but fickle friends\nGreek God, good God\nGreek God\n\nI don't really like how you never shut up\n'Cause you got dirt on everyone\nAnd since you always swear that you wanted me gone\nThen why don't you go get your gun?\n'Cause you don't really hate me\n(You're a little baby)\nYou don't wanna end me\n(You wanna befriend me)\nAnd it's not surprising\n(I can see you smiling)\nEvery time you kick me\nYou're not gonna win me\n\n'Cause I know what you really want\nA little more confidence\nThis is where it's gotta stop\nI'm tired of hearin' it\nYou're just gonna be a fraud\nOh, with nothin' but fickle friends\nGreek God, good God\nGreek God\n\nI don't care about your little threats\nAll the kids in your clique are pretend\nI don't mind when you play with my head\nI flip around, play with yours instead\nI don't like what you said to my friends\nOne day you're gonna regret\nEver messin' with them\n\n'Cause I know what you really want\nA little more confidence\nThis is where it's gotta stop\nI'm tired of hearin' it\nYou're just gonna be a fraud\nOh, with nothin' but fickle friends\nGreek God, good God\nGreek God",
        traduccion:"Oh, realmente no me importa si te gusto o no\nPero sé que tú también me quieres\nOh, cualquier cosa que haga, sé que vas a ver\nPara rumorear que soy un tonto\nTú y todos tus amigos tienen que caminar en un escuadrón\nPorque son tan inseguros\nOh, sobrecompensar porque me estás midiendo\nEl truco más antiguo del libro\n\nNo hay nada que puedas hacer\nPara amortiguar mi humor\nNo hay nada que puedas decir\nNo te gustará de todos modos\nSé que te han herido\nNo significa que sea nuestro turno\n\nPorque sé lo que realmente quieres\nUn poco más de confianza\nAquí es donde tiene que parar\nEstoy cansado de oírlo\nSolo vas a ser un fraude\nOh, no somos más que amigos inconstantes\nDios griego, Dios bueno\nDios griego\n\nNo me gusta que nunca te calles\nPorque tienes la suciedad de todo el mundo\nY como siempre juraste que querías que me fuera\nEntonces, ¿por qué no vas a buscar tu arma?\nPorque no me odias de verdad\n(Eres un pequeño bebé)\nNo quieres acabar conmigo\n(Quieres ser mi amigo)\nY no es sorprendente\n(Puedo verte sonriendo)\nCada vez que me das una patada\nNo me vas a ganar\n\nPorque sé lo que realmente quieres\nUn poco más de confianza\nAquí es donde tiene que parar\nEstoy cansado de oírlo\nSolo vas a ser un fraude\nOh, no somos más que amigos inconstantes\nDios griego, Dios bueno\nDios griego\n\nNo me importan tus pequeñas amenazas\nTodos los chicos de tu camarilla están fingiendo\nNo me importa cuando juegas con mi cabeza\nDoy la vuelta, juego con el tuyo en su lugar\nNo me gusta lo que le dijiste a mis amigos\nUn día te vas a arrepentir\nSiempre te has metido con ellos\n\nPorque sé lo que realmente quieres\nUn poco más de confianza\nAquí es donde tiene que parar\nEstoy cansado de oírlo\nSolo vas a ser un fraude\nOh, no somos más que amigos inconstantes\nDios griego, Dios bueno\nDios griego",
        video:"https://www.youtube.com/embed/5AZYUT5Sn38?si=8Gs3bStK0BMLQffC",
        reproductor:"/Audios/GreekGod.mp3"
    },
    Lookalike:{
        tittle:"Lookalike",
        textColor: "rgb(245, 106, 81)",
        back:"Songs.html?album=Sunsetseason",
        fondo:"/Images/SunsetSeason.jpg",
        letra:"Let's go back to the summer night\nWhen we met eyes, it's like a movie line\nKissing underneath the city lights\nBut now you're laying in another guy's arms\n'Cause I'm all gone\n\nBut when you look in his eyes\nDo you think of mine?\nAnd when you look at that smile\nDo I cross your mind?\nI know in your head\nYou see me instead\n'Cause he looks a lot like I did back then\nBaby, don't lie\nHe's just a lookalike\n\nCan't redo what's already done\nCan't compete 'cause I've already won\nSaying, this time: It's really love\nBut honey, you're not fooling anyone\nDon't you know we're done?\n\nBut when you look in his eyes\nDo you think of mine?\nAnd when you look at that smile\nDo I cross your mind?\nI know in your head\nYou see me instead\n'Cause he looks a lot like I did back then\nBaby, don't lie\nHe's just a lookalike\n\nAnd I'll admit that I sometimes, maybe, might\nThink about you at night, well, almost every night\nNo matter how I try to hide\nAnd erase you from my mind\nI'm dying to find a lookalike\n\n'Cause when you look in his eyes\nHope you think of mine\nAnd when you look at that smile\nHope I cross your mind\nI hope in your head\nYou see me instead\n'Cause you've been in mine every day since then\nMaybe it's time to find a lookalike\n\nNo, I can't lie\nI need a lookalike",
        traduccion:"Volvamos a la noche de verano\nCuando nos vimos, como en una línea de película\nBesándonos bajo la luz de la ciudad\nPero ahora estas acostado en los brazos de otro chico\nPorque ya no estoy\n\nPero cuando ves sus ojos\n¿Piensas en los míos?\nY cuando ves su sonrisa\n¿Paso por tu mente?\nSé que en tu cabeza\nMe ves a mi\nPorque él se parece mucho a como yo era aquel entonces\nBebé no mientas\nÉl solo es un doble\n\nNo puedo volver hacer lo que ya se hizo\nNo puedo competir, porque ya gané\nDices que esta vez es realmente amor\nPero cariño, no estas engañando a nadie\n¿No sabes que acabamos?\n\nPero cuando ves sus ojos\n¿Piensas en los míos?\nY cuando ves su sonrisa\n¿Paso por tu mente?\nSé que en tu cabeza\nMe ves a mi\nPorque él se parece mucho a como yo era aquel entonces\nBebé no mientas\nÉl solo es un doble\n\nY admito que algunas veces, tal vez, quizá\nPiense en ti en la noche, bueno, casi todas las noches\nSin importar cómo intento ocultarte\nY borrarte de mi mente\nEstoy muriendo\nPor encontrar un doble\n\nPorque cuando ves sus ojos\nEspero que pienses en los míos\nY cuando ves su sonrisa\nEspero pasar por tu mente\nEspero que en tu cabeza\nMe veas a mi\nPorque tu haz estado en la mía desde aquel día\nTal vez es tiempo de encontrar a un doble\n\nNo, no puedo mentir\nNecesito a un doble",
        video:"https://www.youtube.com/embed/8E63J9eINIE?si=jyAsuN79qoCS5YK5",
        reproductor:"/Audios/lookalike.mp3"
    },
    ComfortCrowd:{
        tittle:"Comfort Crowd",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"This hurt that I'm holding's getting heavy\nBut I'ma keep a smile on my shoulders till I'm sweaty\nBegging on my knees\nScreaming: Someone come and help me\nBut by the time they're there\nI've already hid the body\n\nMy breath's getting short and I'm unsteady\nWelling up in tears as I lay upon your belly\nTelling you: I'm fine\nI don't really need nobody\nBut you say through a sigh\nThat I said that lie already\n\nI just needed company now\nYeah, I just needed someone around\nYeah, I don't care what song that we play\nOr mess that we make\nJust company now\nComfort crowd\nComfort crowd\n\nWe rot, thinking lots about nothing\nYeah, I could spend a lifetime\nSitting here talking\nAnd even if I cry all over your body\nYou don't really mind\nSay you like your shirt soggy\n\nYeah, I just needed company now\nYeah, I just needed someone around\nYeah, I don't care what song that we play\nOr mess that we make\nJust company now\nComfort crowd\nComfort crowd\n\nWe mess around\nAnd laugh too loud\nAnd make the sounds\nWe try to hide when people are around\nBy blood we're bound\nThrough ups and downs\nTheir smiles and pouts\nComfort crowd\nYou can always count\n\nYeah, I just needed company now\nYeah, I just needed someone around\nYeah, I don't care what song that we play\nOr mess that we make\nJust company now\nComfort crowd",
        traduccion:"Este dolor que llevo se está volviendo pesado\nPero mantendré una sonrisa en mis labios hasta sudar\nRogando de rodillas\nGritando: ¡Alguien venga a ayudarme!\nPero para cuando llegan\nYa he escondido el cuerpo\n\nMi respiración se acorta y estoy inestable\nLlenándome de lágrimas mientras me recuesto en tu vientre\nDiciéndote: Estoy bien\nNo necesito a nadie\nPero tú dices con un suspiro\nQue ya he dicho esa mentira antes\n\nSolo necesitaba compañía ahora\nSí, solo necesitaba a alguien cerca\nSí, no me importa qué canción toquemos\nO el desorden que hagamos\nSolo compañía ahora\nGente que da consuelo\nGente que da consuelo\n\nNos pudrimos, pensando mucho en nada\nSí, podría pasar una vida\nSentado aquí hablando\nY aunque llore sobre tu cuerpo\nRealmente no te importa\nDices que te gusta la camisa empapada\n\nSí, solo necesitaba compañía ahora\nSí, solo necesitaba a alguien cerca\nSí, no me importa qué canción toquemos\nO el desorden que hagamos\nSolo compañía ahora\nGente que da consuelo\nGente que da consuelo\n\nNos divertimos\nY reímos demasiado fuerte\nY hacemos los sonidos\nQue tratamos de ocultar cuando hay gente cerca\nPor la sangre estamos unidos\nA través de altos y bajos\nSus sonrisas y muecas\nGente que da consuelo\nSiempre puedes contar con ellos\n\nSí, solo necesitaba compañía ahora\nSí, solo necesitaba a alguien cerca\nSí, no me importa qué canción toquemos\nO el desorden que hagamos\nSolo compañía ahora\nGente que da consuelo",
        video:"https://www.youtube.com/embed/eBHHGXT9bRs?si=XHXIiXdxec0BYvA7",
        reproductor:"/Audios/comfort.mp3"
    },
    WishYouWereSober:{
        tittle:"Wish You Were Sober",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"Wish you were so–, wish you were so–, wish you were sober\n(Sober, sober, sober)\n\nThis party's shit, wish we could dip\nGo anywhere but here\nDon't take a hit, don't kiss my lips\nAnd please don't drink more beer\n\nI'ma crawl out of the window now\n'Cause I don't like anyone around\nKinda hope you're following me out\nBut this is definitely not my crowd\n\n19 but you act 25 now\nKnees weak, but you talk pretty proud, wow\nRipped jeans and a cup that you just downed\nTake me where the music ain't too loud\nTrade drinks, but you don't even know her\nSave me till the party is over\nKiss me in the seat of your Rover\nReal sweet, but I wish you were sober\n\n(Wish you were so–, wish you were so–, wish you were sober)\nI wish you were sober\n(Wish you were so–, wish you were so–, wish you were sober)\nI wish you were sober\n\nTrip down the road, walking you home\nYou kiss me at your door\nPulling me close, beg me stay over\nBut I'm over this roller coaster\n\nI'ma crawl out of the window now\nGetting good at saying: Gotta bounce\nHonestly, you always let me down\nAnd I know we're not just hanging out\n\n19 but you act 25 now\nKnees weak, but you talk pretty proud, wow\nRipped jeans and a cup that you just downed\nTake me where the music ain't too loud\nTrade drinks, but you don't even know her\nSave me till the party is over\nKiss me in the seat of your Rover\nReal sweet, but I wish you were sober\n\n(Wish you were so–, wish you were so–, wish you were sober)\nI wish you were sober\n(Wish you were so–, wish you were so–, wish you were sober)\nI wish you were sober\n\nI wish, I wish, I wish, I wish, I wish\nI wish you were sober\nI wish, I wish, I wish, I wish, I wish\nOh, I wish you were sober\n\n19 but you act 25 now\nKnees weak, but you talk pretty proud, wow\nRipped jeans and a cup that you just downed\nTake me where the music ain't too loud\nTrade drinks, but you don't even know her\nSave me till the party is over\nKiss me in the seat of your Rover\nReal sweet, but I wish you were sober",
        traduccion:"Desearía que estuvieras so-, desearía que estuvieras so-, desearía que estuvieras sobrio\n(Sobrio, sobrio, sobrio)\n\nEsta fiesta es una mierda, ojalá pudiéramos sumergirnos\nVe a cualquier lugar menos aquí\nNo te des un golpe, no beses mis labios\nY por favor no bebas más cerveza\n\nAhora me arrastraré por la ventana\nPorque no me gusta que nadie esté cerca\nEspero que me estés siguiendo\nPero definitivamente no es mi público\n\nDiecinueve pero ahora actúas 25\nLas rodillas débiles, pero hablas muy orgulloso, wow\nVaqueros rotos y una taza que acabas de tirar\nLlévame donde la música no esté muy alta\nIntercambia bebidas, pero ni siquiera la conoces\nSálvame hasta que la fiesta termine\nBésame en el asiento de tu Rover\nMuy dulce, pero desearía que estuvieras sobrio\n\nDesearía que estuvieras so-, desearía que estuvieras so-, desearía que estuvieras sobrio\nDesearía que estuvieras sobrio\nDesearía que estuvieras so-, desearía que estuvieras so-, desearía que estuvieras sobrio\nDesearía que estuvieras sobrio\n\nViaje por el camino, caminando a casa\nMe besas en tu puerta\nAcercándome, rogándome que me quede a dormir\nPero ya he superado esta montaña rusa\n\nAhora me arrastraré por la ventana\nSe está volviendo bueno en decir, tiene que rebotar\nHonestamente, siempre me decepcionas\nY sé que no solo estamos pasando el rato\n\nDiecinueve pero ahora actúas 25\nLas rodillas débiles, pero hablas muy orgulloso, wow\nVaqueros rotos y una taza que acabas de tirar\nLlévame donde la música no esté muy alta\nIntercambia bebidas, pero ni siquiera la conoces\nSálvame hasta que la fiesta termine\nBésame en el asiento de tu Rover\nMuy dulce, pero desearía que estuvieras sobrio\n\nDesearía que estuvieras so-, desearía que estuvieras so-, desearía que estuvieras sobrio\nDesearía que estuvieras sobrio\nDesearía que estuvieras so-, desearía que estuvieras so-, desearía que estuvieras sobrio\nDesearía que estuvieras sobrio\n\nDeseo, deseo, deseo, deseo, deseo, deseo\nDesearía que estuvieras sobrio\nDeseo, deseo, deseo, deseo, deseo, deseo\nDesearía que estuvieras sobrio\n\nDiecinueve pero ahora actúas 25\nLas rodillas débiles, pero hablas muy orgulloso, wow\nVaqueros rotos y una taza que acabas de tirar\nLlévame donde la música no esté muy alta\nIntercambia bebidas, pero ni siquiera la conoces\nSálvame hasta que la fiesta termine\nBésame en el asiento de tu Rover\nMuy dulce, pero desearía que estuvieras sobrio",
        video:"https://www.youtube.com/embed/hEDBZtmKPmg?si=pN282vcfyZUGaWf_",
        reproductor:"/Audios/wyws.mp3"
    },
    Overdrive:{
        tittle:"Overdrive",
        textColor: "rgb(252, 255, 61)",
        back:"index.html",
        fondo:"/Images/overdrive.jpg",
        letra:"Only met on the weekend\nSaid I'm not catching feelings\nOh, I guess I lied (lied, lied)\nDiving off of the deep end\nI can't think of a reason\nWe should take our time (time)\nOoh\n\nAll or nothing\nLet's just trust the night\nOoh, ooh\n\nBurning down the street, no left-right, left-right\nI don't wanna see no red light, red light\nFast lane on the beat, go ten-five, ten-five\nYou right next to me, feel the heat going overdrive\nGoing overdrive, yeah\n\nYeah, I know you're a stranger\nBut I'm liking the danger\nOf the I don't know (know, know)\nDon't give a fuck about labels\nThrow the dice on the table\nAnd just let 'em roll (roll)\nOoh\n\nAll or nothing\nLet's just trust the night\nOoh, ooh\n\nBurning down the street, no left-right, left-right\nI don't wanna see no red light, red light\nFast lane on the beat, go ten-five, ten-five\nYou right next to me, feel the heat going overdrive\nGoing overdrive, yeah\n\nAll or nothing\nLet's just trust the night, night\nAll or nothing\nYou're my ride or die\nOoh, ooh\n\nBurning down the street, no left-right, left-right\nI don't wanna see no red light, red light\nFast lane on the beat, go ten-five, ten-five\nYou right next to me, feel the heat going overdrive (ooh)\nGoing overdrive, yeah\nGoing overdrive\nGoing overdrive, yeah",
        traduccion:"Sólo se reunió el fin de semana\nDijo que no estoy captando sentimientos\nOh, supongo que mentí (mentido, mentido)\nBucear fuera del extremo profundo\nNo puedo pensar en una razón\nDeberíamos tomarnos nuestro tiempo (tiempo)\nOh\n\nTodo o nada\nConfiemos en la noche\nOh, oh\n\nCorriendo por la calle no izquierda derecha, izquierda derecha\nNo quiero ver ninguna luz roja, luz roja\nDeslizamiento de tierra en el ritmo van diez cinco, diez cinco\nTú justo a mi lado, sientes el calor sobrevolando\nIr de sobremarcha, sí\n\nSí, sé que eres un extraño\nPero me gusta el peligro\nDe la no sé (saber, saber)\nNo me importan un carajo las etiquetas\nTira los dados sobre la mesa\nY déjalos rodar (rodar)\nOh\n\nTodo o nada\nConfiemos en la noche\nOh, oh\n\nCorriendo por la calle no izquierda derecha, izquierda derecha\nNo quiero ver ninguna luz roja, luz roja\nDeslizamiento de tierra en el ritmo van diez cinco, diez cinco\nTú justo a mi lado, sientes el calor sobrevolando\nIr de sobremarcha, sí\n\nTodo o nada\nConfiemos en la noche, noche\nTodo o nada\nEres mi coche o mueres\nOh, oh\n\nCorriendo por la calle no izquierda derecha, izquierda derecha\nNo quiero ver ninguna luz roja, luz roja\nDeslizamiento de tierra en el ritmo van diez cinco, diez cinco\nUsted justo a mi lado, siente el calor\nIr overdrive\nIr de sobremarcha, sí\nIr overdrive\nIr de sobremarcha, sí",
        video:"https://www.youtube.com/embed/NDpwh0pCXDw?si=wTcANCSGjEVWfKYG",
        reproductor:"/Audios/overdrive.mp3"
    },
    TheKing:{
        tittle:"The King",
        textColor: "rgb(19, 120, 235)",
        back:"index.html",
        fondo:"/Images/TheKing.jpg",
        letra:"Crush always making me feel like I've got nothing to offer\nBut I'm the only one that can make you feel right\nI'm the only one that you think of at night\nBaby, don't lie\nYou're always talking to me like you're totally bothered\nSo why you always ring at the end of my line?\nDon't you got a girl that can make you feel nice?\nIt's a dead sign\n\nYou see me as your lifeline\nOther boys and girls never really made you feel right\nAnd you can't explain why I'm always running your mind\nDon't you see the answer's right in front of your eyes?\n\nYou like me, well obviously\nSo why you tryna leave when you know that I'm the king?\n(You'll see)\n'Cause I'm supreme\n(Choose me)\nOther lovers give you no luck\n'Cause I'm the only one that has made you fall in love\n(You'll see)\nSo just shut up\n(Choose me)\n\nBabe's always flirting away, getting every number\nAnd you can have your fun 'cause I know that it's fake\nI know when you're done you'll come running my way\nSo I let you\nDate everyone and complain that you can't find a lover\n'Cause I'm the only one when the chemistry fades\nI'm the only one at the end of the day\nKinda cliché\n\nYou see me as your lifeline\nOther boys and girls never really made you feel right\nAnd you can't explain why I'm always running your mind\nDon't you see the answer's right in front of your eyes?\n\nYou like me, well obviously\nSo why you tryna leave when you know that I'm the king?\n(You'll see)\n'Cause I'm supreme\n(Choose me)\nOther lovers give you no luck\n'Cause I'm the only one that has made you fall in love\n(You'll see)\nSo just shut up\n(Choose me)\n\nI'm the one you come to when you're feeling alone\nAnd I'm the only one who's gonna pick up the phone\nLooking for the one but it's me all along\n(Choose me)\nBaby, I'm a winner, yeah, it's something you've known\nNo, I'm not a quitter, yeah, I get what I want\nPlaying with your heart could you give me the throne?\nChoose me\n\nYou like me, well obviously\nSo why you tryna leave when you know that I'm the king?\n(You'll see)\n'Cause I'm supreme\n(Choose me)\nOther lovers give you no luck\n'Cause I'm the only one that has made you fall in love\n(You'll see)\nSo just shut up\n(Choose me)",
        traduccion:"Mi enamoramiento siempre me hace sentir que no tengo nada que ofrecer\nPero soy el único que puede hacerte sentir bien\nSoy el único en el que piensas por la noche\nNena, no mientas\nSiempre me hablas como si estuvieras totalmente molesto\nEntonces, ¿por qué siempre llamas al final de mi línea?\n¿No tienes una chica que te haga sentir bien?\nEs una señal muerta\n\nMe ves como tu salvavidas\nOtros chicos y chicas nunca te hicieron sentir bien\nY no puedes explicar por qué siempre estoy manejando tu mente\n¿No ves que la respuesta está justo delante de tus ojos?\n\nTe gusto, oh, obviamente\nEntonces, ¿por qué intentas irte cuando sabes que soy el rey?\n(Ya verás)\nPorque soy supremo\n(Elígeme)\nOtros amantes no te dan suerte\nPorque soy el único que ha hecho que te enamores\n(Ya verás)\nAsí que cállate\n(Elígeme)\n\nLas chicas siempre coqueteando, consiguiendo cada número\nY puedes divertirte porque sé que es falso\nSé que cuando termines vendrás corriendo hacia mí\nAsí que te dejé\nSalir con todo el mundo y quejarte de que no puedes encontrar un amante\nPorque soy el único cuando la química se desvanece\nSoy el único al final del día\nUn poco cliché\n\nMe ves como tu salvavidas\nOtros chicos y chicas nunca te hicieron sentir bien\nY no puedes explicar por qué siempre estoy manejando tu mente\n¿No ves que la respuesta está justo delante de tus ojos?\n\nTe gusto, oh, obviamente\nEntonces, ¿por qué intentas irte cuando sabes que soy el rey?\n(Ya verás)\nPorque soy supremo\n(Elígeme)\nOtros amantes no te dan suerte\nPorque soy el único que ha hecho que te enamores\n(Ya verás)\nAsí que cállate\n(Elígeme)\n\nSoy a la que vienes cuando te sientes solo\nY soy el único que va a coger el teléfono\nBuscando a la única, pero soy yo todo el tiempo\n(Elígeme)\nNena, soy el único, sí, eso es algo que has sabido\nNo, no soy un desertor, sí, obtengo lo que quiero\nJugando con tu corazón porque me das el trono\nElígeme\n\nTe gusto, oh, obviamente\nEntonces, ¿por qué intentas irte cuando sabes que soy el rey?\n(Ya verás)\nPorque soy supremo\n(Elígeme)\nOtros amantes no te dan suerte\nPorque soy el único que ha hecho que te enamores\n(Ya verás)\nAsí que cállate\n(Elígeme)",
        video:"https://www.youtube.com/embed/8SUhGnd4fsU?si=XIItjjuZbKZYncUq",
        reproductor:"/Audios/TheKing.mp3"
    },
    Maniac:{
        tittle:"Maniac",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"(Maniac)\n\nYou were with your friends, partyin'\nWhen the alcohol kicked in\nSaid you wanted me dead\nSo, you show up at my home, all alone\nWith a shovel and a rose\nDo you think I'm a joke?\n\n'Cause people like you always want back what they can't have\nBut I'm past that and you know that\nSo you should turn back to your rat pack, tell 'em I'm trash\n\nTell all of your friends that I'm crazy and drive you mad\nThat I'm such a stalker, a watcher, a psychopath\nAnd tell them you hate me and dated me just for laughs\nSo, why do you call me and tell me you want me back?\nYou maniac\n\n(Maniac, some may say that I'm a) you maniac\n(Maniac, some may say that I'm a) you maniac\n(Maniac, some may say that I'm a) you maniac\n(Maniac, some may say that I'm)\n\nYou just went too far\nWrecked your car, called me crying in the dark\nNow you're breakin' my heart\nSo, I show up at your place right away\nWipe the tears of your face\nWhile you beg me to stay\n\nWell, people like you always want back what they can't have\nBut I'm past that and you know that\nSo you should turn back to your rat pack, tell 'em I'm trash\n\nTell all of your friends that I'm crazy and drive you mad\nThat I'm such a stalker, a watcher, a psychopath\nAnd tell them you hate me and dated me just for laughs\nSo, why do you call me and tell me you want me back?\nYou maniac\n\n(Maniac, some may say that I'm a) you maniac\n(Maniac, some may say that I'm a) you maniac\n(Maniac, some may say that I'm a) you maniac\n(Maniac, some may say that I'm)\n\nPsychopathic, don't be so dramatic\nWe had magic, but you made it tragic\nNow you're manic, honestly, I've had it\nListen to yourself, think you need to get some help\n\nTell all of your friends that I'm crazy and drive you mad\nThat I'm such a stalker, a watcher, a psychopath\nAnd tell them you hate me and dated me just for laughs\nSo, why do you call me and tell me you want me back?\nYou maniac\n\n(Maniac, some may say that I'm a) you maniac\n(Maniac, some may say that I'm a) you maniac\n(Maniac, some may say that I'm a) you maniac\n(Maniac, some may say that I'm)",
        traduccion:"(Maníaco)\n\nEstabas con tus amigos, de fiesta\nCuando el alcohol hizo efecto\nDijiste que querías verme muerto\nAsí que llegas a mi casa, solo\nCon una pala y una rosa\n¿Acaso crees que soy una broma?\n\nPorque la gente como tú siempre quiere lo que no puede tener\nPero yo ya pasé por eso, y lo sabes\nAsí que deberías volver con tu grupo de ratas y decirles que soy basura\n\nDile a todos tus amigos que estoy loco y te vuelvo loco\nQue soy un acosador, un vigilante, un psicópata\nY diles que me odias y que saliste conmigo solo por diversión\nEntonces, ¿por qué me llamas y me dices que me quieres de vuelta?\nEres un maníaco\n\n(Maníaco, algunos dirían que soy un) maníaco\n(Maníaco, algunos dirían que soy un) maníaco\n(Maníaco, algunos dirían que soy un) maníaco\n(Maníaco, algunos dirían que soy un)\n\nTe pasaste de la raya\nDestrozaste tu auto, me llamaste llorando en la oscuridad\nAhora estás rompiéndome el corazón\nAsí que llego a tu casa de inmediato\nLimpiando las lágrimas de tu rostro\nMientras me ruegas que me quede\n\nBueno, la gente como tú siempre quiere lo que no puede tener\nPero yo ya pasé por eso, y lo sabes\nAsí que deberías volver con tu grupo de ratas y decirles que soy basura\n\nDile a todos tus amigos que estoy loco y te vuelvo loco\nQue soy un acosador, un vigilante, un psicópata\nY diles que me odias y que saliste conmigo solo por diversión\nEntonces, ¿por qué me llamas y me dices que me quieres de vuelta?\nEres un maníaco\n\n(Maníaco, algunos dirían que soy un) maníaco\n(Maníaco, algunos dirían que soy un) maníaco\n(Maníaco, algunos dirían que soy un) maníaco\n(Maníaco, algunos dirían que soy un)\n\nPsicopático, no seas tan dramático\nTuvimos magia, pero lo hiciste trágico\nAhora estás maniaca, honestamente, ya no aguanto\nEscúchate a ti mismo, creo que necesitas ayuda\n\nDile a todos tus amigos que estoy loco y te vuelvo loco\nQue soy un acosador, un vigilante, un psicópata\nY diles que me odias y que saliste conmigo solo por diversión\nEntonces, ¿por qué me llamas y me dices que me quieres de vuelta?\nEres un maníaco\n\n(Maníaco, algunos dirían que soy un) maníaco\n(Maníaco, algunos dirían que soy un) maníaco\n(Maníaco, algunos dirían que soy un) maníaco\n(Maníaco, algunos dirían que soy un)",
        video:"https://www.youtube.com/embed/-E-_IRJU5w0?si=jkpGb4n74YD78KUe",
        reproductor:"/Audios/maniac.mp3"
    },
    OnlineLove:{
        tittle:"(Online Love)",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"You only pass through my city\nEvery once in a million seconds on a broken clock\nYet we talk like we're living\nOnly miles, only minutes from another just around the block\nAs I stare at my screen, shining blue and green\nAll alone in a coffee shop\nI can't help but imagine what maybe could've happened\nIf you weren't just an online love\n\nSometimes I say hi and he, like, doesn't answer\nMaybe, okay, maybe he's just in a bad mood\nI think he's just, I think he's just going through something\n(Delete)",
        traduccion:"Solo pasas por mi ciudad\nCada vez que el reloj se descompone, en uno de esos raros momentos\nY aun así, hablamos como si viviéramos\nA solo unas calles de distancia, como si estuviéramos cerca el uno del otro\nMientras miro mi pantalla, brillando en azul y verde\nSolo, en una cafetería\nNo puedo evitar imaginar lo que pudo haber pasado\nSi no fueras solo un amor en línea\n\nA veces te saludo y tú no contestas\nQuizás, tal vez, solo estás de mal humor\nCreo que solo estás pasando por algo\n(Borrar)",
        video:"https://www.youtube.com/embed/er7ZrLsp5g0?si=ECIQ5lwlTfEVtEo2",
        reproductor:"/Audios/OnlineLove.mp3"
    },
    Checkmate:{
        tittle:"Chekcmate",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"You think you're funny right?\nCallin' me drunk when it's too late at night\nTellin' me truth that you know all are lies\nYeah, you think you're funny, right? (What?)\nYou think you're super sly\nFlirtin' with them but tellin' me you're mine\nBuildin' me up, but buttercup, you lied\nNow I'm gonna ruin your life\n\n'Cause I've gotten tired of the games that you play\nWhen you tell me you love me then you throw me away\nSo cry me a river till you drown in the lake\n'Cause you may think you're winnin' but checkmate\nYeah, you may think you're winnin' but checkmate\n\nNow this is gettin' fun\nI saw you kissing someone else's tongue\nYou said that I'm the only one you love\nBaby this is gettin' fun\nI'll let you think you won\nDate in the park, I'll play it super dumb\nHolding your hand but then the other one\nI'm holding a loaded gun\nYeah, baby you should really run\n\n'Cause I've gotten tired of the games that you play\nWhen you tell me you love me then you throw me away\nSo cry me a river till you drown in the lake\n'Cause you may think you're winnin' but checkmate\nYeah, you may think you're winnin' but checkmate\n\nAnd I'ma get you gone\nCan't play me like your pawn\nSet fire to your lawn\nJust like you did to my heart\nAnd I'ma wreck your car (and I'ma wreck your car)\nAnd max your credit card (and max your credit card)\nA lover on the large (a lover on the large)\nYou're gonna wish you never harmed me\n\n'Cause I've gotten tired of the games that you play\nWhen you tell me you love me then you throw me away\nSo cry me a river till you drown in the lake\n'Cause you may think you're winning but checkmate\n\nAnd you did some damage so I'm making you pay\nAnd no one's ever gonna love you anyways\n'Cause you're just a narcissist who's totally fake\nYeah, you may think you're winnin' this heartbreak\nBut you aren't gonna win it 'cause checkmate",
        traduccion:"¿Crees que eres gracioso, verdad?\nLlamándome borracho cuando ya es muy tarde en la noche\nDiciéndome verdades que sabes que son puras mentiras\nSí, ¿crees que eres gracioso, verdad? (¿Qué?)\n¿Crees que eres todo un astuto?\nCoqueteando con otros mientras me dices que soy solo tuyo\nJugando conmigo, pero la verdad es que me mentiste\nAhora voy a arruinarte la vida\n\nPorque ya me cansé de los juegos que juegas\nCuando me dices que me amas y luego me tiras a un lado\nAsí que llora un río hasta que te ahogues en el lago\nPorque quizá pienses que estás ganando, pero jaque mate\nSí, quizá pienses que estás ganando, pero jaque mate\n\nAhora esto se está poniendo interesante\nTe vi besando a alguien más\nDijiste que yo era el único a quien amabas\nCariño, esto se está poniendo interesante\nTe dejaré pensar que ganaste\nSaldremos al parque, yo me haré el tonto\nTomando tu mano, pero en la otra\nEstoy sosteniendo un arma cargada\nSí, cariño, deberías correr\n\nPorque ya me cansé de los juegos que juegas\nCuando me dices que me amas y luego me tiras a un lado\nAsí que llora un río hasta que te ahogues en el lago\nPorque quizá pienses que estás ganando, pero jaque mate\nSí, quizá pienses que estás ganando, pero jaque mate\n\nY te voy a sacar de mi vida\nNo puedes jugar conmigo como si fuera tu peón\nPrenderé fuego a tu jardín\nIgual que tú hiciste con mi corazón\nY voy a destrozar tu auto (y voy a destrozar tu auto)\nY a reventar tu tarjeta de crédito (y a reventar tu tarjeta de crédito)\nUn enamorado en fuga (un enamorado en fuga)\nVas a desear no haberme hecho daño\n\nPorque ya me cansé de los juegos que juegas\nCuando me dices que me amas y luego me tiras a un lado\nAsí que llora un río hasta que te ahogues en el lago\nPorque quizá pienses que estás ganando, pero jaque mate\n\nY me hiciste daño, así que ahora vas a pagar\nY nadie te va a amar de verdad\nPorque eres solo un narcisista, completamente falso\nSí, quizá pienses que estás ganando este desamor\nPero no vas a ganarlo, porque jaque mate",
        video:"https://www.youtube.com/embed/5WsvJaUAWlU?si=6aHgoPXHyNyF4rGq",
        reproductor:"/Audios/checkmate.mp3"
    },
    TheCutThatAlwaysBleeds:{
        tittle:"The Cut That Always Bleeds",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"I don't love you anymore\nA pretty line that I adore\nFive words that I've heard before\n'Cause you keep me on a rope\nAnd tied a noose around my throat\nYou're gone, then back at my door\n\n'Cause if you're gonna leave, better leave, better do it fast\nCan't live a little longer sittin' on your lap\n'Cause you know what you're doin' when you're comin' back\nAnd I don't wanna have another heart attack\n\nOh, I can't be your lover on a leash\nEvery other week, when you please\nOh, I can't be the kiss that you don't need\nThe lie between your teeth\nThe cut that always bleeds (ah-ah-ah)\nThe cut that always bleeds (ah-ah-ah)\n\nSay you love somebody new\nThen beat my heart to black and blue\nThen they leave, and it's me you come back to (ah-ah-ah)\nTo say you loved me all along\nAnd kiss the bruises till they're gone\nBittersweet, 'cause I can't breathe inside your arms\n\n'Cause if you're gonna leave, better leave, better do it fast\nCan't live another minute bleedin' from my back\n'Cause I don't have another one for you to stab\nAnd I don't wanna have another heart attack\n\nOh, I can't be your lover on a leash\nEvery other week, when you please\nOh, I can't be the kiss that you don't need\nThe lie between your teeth\nThe cut that always bleeds (ah-ah-ah)\nThe cut that always bleeds (ah-ah-ah)\n\n(Ooh) but even though you're killin' me, yeah\n(Ooh) I need you like the air I breathe\n(Ooh) I need, I need you more than me\n(Ooh) I need you more than anything\n(Ooh) please, please\n\n'Cause I could be your lover on a leash\nEvery other week, when you please\nOh, I could be anything you need\nAs long as you don't leave\nThe cut that always",
        traduccion:"Yo ya no te amo\nUna linda frase que adoro\nCinco palabras que he escuchado antes\nPorque me mantienes en una cuerda\nY ataste un nudo alrededor de mi garganta\nTe vas y después regresas a mi puerta\n\nPorque si te vas a ir, mejor vete, mejor hazlo rápido\nNo puedo seguir viviendo sentado en tu regazo\nPorque tú sabes lo que me haces cada vez que regresas\nY no quiero otro ataque al corazón\n\nOh, yo no puedo ser tu amante con una correa\nCada dos semanas, cuando tú quieras\nOh, yo no puedo ser el beso que no necesitas\nLa mentira entre tus dientes\nLa herida que siempre sangra (ah-ah-ah)\nLa herida que siempre sangra (ah-ah-ah)\n\nDices que amas a alguien nuevo\nY golpeas mi corazón hasta dejarlo herido\nY te dejan, y es a mi con quien regresas\nPara decirme que siempre me amaste\nY beses mis moretones hasta que los hagas desaparecer\nEs agridulce, porque no puedo respirar dentro de tus brazos\n\nPorque si te vas a ir, mejor vete, mejor hazlo rápido\nNo puedo vivir otro minuto sangrando de mi espalda\nPorque no tengo otra para que la puedas apuñalar\nY no quiero tener otro ataque al corazón\n\nOh, yo no puedo ser tu amante con una correa\nCada dos semanas, cuando tú quieras\nOh, yo no puedo ser el beso que no necesitas\nLa mentira entre tus dientes\nLa herida que siempre sangra (ah-ah-ah)\nLa herida que siempre sangra (ah-ah-ah)\n\n(Ooh-ooh-ooh) pero a pesar de que me estas matando, si\n(Ooh-ooh-ooh) te necesito como el aire que respiro\n(Ooh-ooh-ooh) te necesito, te necesito mas que a mí\n(Ooh-ooh-ooh) te necesito mas que a nada\n(Ooh-ooh-ooh) por favor, por favor\n\nPorque, yo podría ser tu amante con una correa\nCada dos semanas, cuando tú quieras\nOh, yo podría ser cualquier cosa que necesites\nMientras que no te vayas\nLa herida que siempre",
        video:"https://www.youtube.com/embed/OuTLKgPyaF0?si=0UFdLHJsi-69xRsB",
        reproductor:"/Audios/tctab.mp3"
    },
    FightOrFlight:{
        tittle:"Fight Or Flight",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"Something's gotten into you\nYou don't really look at me the way you used to\nAnd I'm hoping it ain't true\nEvery single rumor that I've heard of you\n\nSay you were off with someone that I don't know\nCallin' other people on your telephone\nKinda wish I didn't know\n\nWell, fight or flight, I'd rather die\nThan have to cry in front of you\nFight or flight, I'd rather lie\nThen tell you I'm in love with you\nMy eyes are welling up\nAs you admit there's someone new\nIt's my move, fight or flight\n\nYou tell me it ain't what it seems\nBut, baby, this is looking like a crime scene\nThere's clothes thrown on the balcony\nAnd you smell like perfume out a magazine\n\nI'm throwing all the shit outta my window\nTelling you I wish that we had never spoke\nBaby, I already know\n\nWell, fight or flight, I'd rather die\nThan have to cry in front of you\nFight or flight, I'd rather lie\nThen tell you I'm in love with you\nMy eyes are welling up\nAs you admit there's someone new\nIt's my move, fight or flight\n\nNow there's someone at my door\nSomeone I've not met before\nThey've got eyes like mine\nA pretty smile\nAnd they've been crying for a while\n'Cause they also didn't know\nThat our lover loved us both\n\nWell, fight or flight, I'd rather die\nThan have to cry in front of you\nFight or flight, I'd rather lie\nThen tell you I'm in love with you\nMy eyes are welling up\nAs you admit there's someone new\nIt's my move, fight or flight",
        traduccion:"Algo se ha metido en ti\nYa no me miras como antes\nY espero que no sea cierto\nTodos los rumores que he escuchado de ti\n\nDi que estabas con alguien que no conozco\nLlamando a otras personas en tu teléfono\nDesearía no saber\n\nBueno, pelea o huye, prefiero morir\nQue tener que llorar delante de ti\nPelea o huye, prefiero mentir\nQue decirte que estoy enamorado de ti\nMis ojos están brotando\nComo admites que hay alguien nuevo\nEs mi movimiento, pelea o huye\n\nMe dices que no es lo que parece\nPero, amor, esto parece la escena de un crimen\nHay ropa tirada en el balcón\nY hueles como el perfume de una revista\n\nEstoy tirando toda la mierda por mi ventana\nDiciéndote que desearía que nunca hubiéramos hablado\nBebé, ya sé\n\nBueno, pelea o huye, prefiero morir\nQue tener que llorar delante de ti\nPelea o huye, prefiero mentir\nQue decirte que estoy enamorado de ti\nMis ojos están brotando\nComo admites que hay alguien nuevo\nEs mi movimiento, pelea o huye\n\nAhora hay alguien en mi puerta\nAlguien que no he conocido antes\nTienen ojos como los míos\nUna bonita sonrisa\nY han estado llorando por un tiempo\nPorque tampoco sabían\nQue nuestro amante nos amaba a ambos\n\nBueno, pelea o huye, prefiero morir\nQue tener que llorar delante de ti\nPelea o huye, prefiero mentir\nQue decirte que estoy enamorado de ti\nMis ojos están brotando\nComo admites que hay alguien nuevo\nEs mi movimiento, pelea o huye",
        video:"https://www.youtube.com/embed/LYd-psJ3QLo?si=bTzOMtyVQWZcTbrN",
        reproductor:"/Audios/fof.mp3"
    },
    Affluenza:{
        tittle:"Affluenza",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"Mama's got a new man\nAnd daddy's got a new mansion to keep\nHe never really calls back\n'Cause he's got too many finances to reap\n\nMoney, money, ain't it funny, honey?\nWhen you get what you need\nBaby, life is a breeze\nMoney, money, get me money, money\nTill I'm bloody, bloody\n\nAll these kids have got affluenza\nGoing wreckin' their daddy's Benz, ah\nCrystal liquor cups and designer drugs, oh, oh\nThey say: Money can't buy you no love\nBut a diamond cheers you right up\nGive me none of your Affluence, oh\nAffluenza, affluenza\n\nEvery day's your birthday\nYou threw a party, but you kinda hate all your friends\nSo you're crying in a driveway\nKillin' time, gettin' high, can't wait till it ends\n\nMoney, money, ain't it funny, honey?\nWhen you get what you need\nBaby, life is a breeze\nMoney, money, get me money, money\nTill I'm bloody, bloody\n\nAll these kids have got affluenza\nGoing wreckin' their daddy's Benz, ah\nCrystal liquor cups and designer drugs, oh, oh\nThey say: Money can't buy you no love\nBut a diamond cheers you right up\nGive me none of your Affluence, oh\nAffluenza, affluenza\n\nFat stacks, cold cash\nYou've always had it real lavish, first-class\nTrust fund, gold tongue\n80 grand in both your hands, but no love\n\nAll these kids have got affluenza\nGoing wreckin' their daddy's Benz, ah\nCrystal liquor cups and designer drugs, oh, oh\nThey say: Money can't buy you no love\nBut a diamond cheers you right up\nGive me none of your Affluence, oh\nAffluenza, affluenza\n\nMhmm\nMhmm\nMhmm",
        traduccion:"Mamá tiene un nuevo hombre\nY papá tiene una nueva mansión que mantener\nNunca devuelve las llamadas\nPorque tiene demasiadas finanzas para cosechar\n\nDinero, dinero, no es gracioso, cariño\nCuando consigues lo que necesitas\nNena, la vida es una brisa\nDinero, dinero, consígueme dinero, dinero\nHasta que esté ensangrentado, ensangrentado\n\nTodos estos chicos tienen riqueza\nVan a destrozar el similar de su padre\nTazas de licor de cristal y drogas de diseño, oh, oh\nDicen: El dinero no puede comprarte ningún amor\nPero un diamante te anima\nNo me vengas con tus ganancias\nAfluencia, afluencia\n\nCada día es tu cumpleaños\nHiciste una fiesta pero odias a todos tus amigos\nAsí que estás llorando en la entrada\nMatar el tiempo, drogarse, no puede esperar hasta que termine\n\nDinero, dinero, no es gracioso, cariño\nCuando consigues lo que necesitas\nNena, la vida es una brisa\nDinero, dinero, consígueme dinero, dinero\nHasta que esté ensangrentado, ensangrentado\n\nTodos estos chicos tienen riqueza\nVan a destrozar el similar de su padre\nTazas de licor de cristal y drogas de diseño, oh, oh\nDicen: El dinero no puede comprarte ningún amor\nPero un diamante te anima\nNo me vengas con tus ganancias\nAfluencia, afluencia\n\nPilas de grasa, dinero en efectivo frío\nSiempre lo has tenido muy lujoso, de primera clase\nFondo fiduciario, lengua de oro\n80 grandes en ambas manos, pero sin amor\n\nTodos estos chicos tienen riqueza\nVan a destrozar el similar de su padre\nTazas de licor de cristal y drogas de diseño, oh, oh\nDicen: El dinero no puede comprarte ningún amor (no puede comprarte ningún amor)\nPero un diamante te anima\nNo me des nada de tu riqueza\nAfluencia, afluencia\n\nMhmmm\nMhmmm\nMhmmm",
        video:"https://www.youtube.com/embed/w6zoRUdZKU4?si=DJW-Q7SfOiTdG84v",
        reproductor:"/Audios/Affluenza.mp3"
    },
    CanWeBeFriends:{
        tittle:"(Can We Be Friend)",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"Could you be my best friend?\nLet's hang out every weekend\nWe're driving every night\nStare at people that we like\nCould you be my best friend?\nI'll tell you all my secrets\nI'll tell you all the times\nThat I wished that I could die\n\nAnd if anybody fucks with you\nThey fuck with me\nSo, if anybody fucks with you\nI'll knock their teeth out (yeah)\nCould you be my best friend?\nCan we be friends?\nCould you be my best friend?\nCan we be friends?",
        traduccion:"¿Podrías ser mi mejor amigo?\nSalgamos todos los fines de semanas\nConducimos todas las noches\nMiramos a la gente que nos gusta\n¿Podrías ser mi mejor amigo?\nTe contaré todos mis secretos\nTe contaré todas las veces\nQue deseé poder morir\n\nY si alguien te jode\nMe joden a mi\nEntonces, si alguien te jode\nLes sacaré los dientes (sí)\n¿Podrías ser mi mejor amigo?\n¿Podemos ser amigos?\n¿Podrías ser mi mejor amigo?\n¿Podemos ser amigos?",
        video:"https://www.youtube.com/embed/x8HyzA2XLwY?si=n7BfwGef1guWDuoy",
        reproductor:"/Audios/CanWeBeFriends.mp3"
    },
    Heather:{
        tittle:"Heather",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"I still remember third of December, me in your sweater\nYou said it looked better on me than it did you\nOnly if you knew how much I liked you\nBut I watch your eyes as she\n\nWalks by\nWhat a sight for sore eyes, brighter than a blue sky\nShe's got you mesmerized while I die\n\nWhy would you ever kiss me?\nI'm not even half as pretty\nYou gave her your sweater, it's just polyester\nBut you like her better\n(Wish I were Heather)\n\nWatch as she stands with her holding your hand\nPut your arm 'round her shoulder, now I'm getting colder\nBut how could I hate her? She's such an angel\nBut then again, kinda wish she were dead as she\n\nWalks by\nWhat a sight for sore eyes, brighter than a blue sky\nShe's got you mesmerized while I die\n\nWhy would you ever kiss me?\nI'm not even half as pretty\nYou gave her your sweater, it's just polyester\nBut you like her better\nI wish I were Heather\n\n(Oh) wish I were Heather\n(Oh, oh) wish I were Heather\n\nWhy would you ever kiss me?\nI'm not even half as pretty\nYou gave her your sweater, it's just polyester\nBut you like her better\nWish I were",
        traduccion:"Todavía recuerdo ese tres de diciembre, yo con tu suéter\nDijiste que se veía mejor en mí que en ti\nSi tan solo supieras cuánto me gustabas\nPero miro tus ojos mientras ella\n\nMientras ella pasa\nQué espectáculo para los ojos cansados, más brillantes que el cielo azul\nElla te tiene hipnotizado mientras me muero\n\n¿Por qué me besarías?\nNo tengo ni la mitad de su belleza\nLe diste tu suéter, es solo poliéster\nPero ella te gusta más\n(Desearía ser Heather)\n\nMe quedo mirando mientras ella sostiene tu mano\nPones tu brazo alrededor de su hombro, ahora me está dando más frío\nPero cómo podría odiarla, ella es un ángel\nPero al instante, como que desearía que estuviera muerta\n\nMientras ella pasa\nQué espectáculo para los ojos cansados, más brillantes que el cielo azul\nElla te tiene hipnotizado mientras yo muero\n\n¿Por qué me besarías?\nNo tengo ni la mitad de su belleza\nLe diste tu suéter, es solo poliéster\nPero ella te gusta más\n(Desearía ser Heather)\n\n(Oh) desearía ser Heather\n(Oh, oh) desearía ser Heather\n\n¿Por qué me besarías?\nNo tengo ni la mitad de su belleza\nLe diste tu suéter, es solo poliéster\nPero ella te gusta más\nDesearía ser",
        video:"https://www.youtube.com/embed/24u3NoPvgMw?si=hQ6b9npz-AmEf2a0",
        reproductor:"/Audios/heather.mp3"
    },
    LittleLeague:{
        tittle:"Little League",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"Do you remember days on our old block?\nMessin' with our neighbors who called the cops\nCould've swore that you and me\nCould get away with anything\nWe'd lay on the grass all day talking\n'Cause we snuck out of class when no one was watching\nI remember you and me\nYeah, I remember everything\n\nBut lately I've been feelin' strange\nAnd everybody's tellin' me to act my age\nI never thought that everything I had would fade away\n\nWhen we were younger\nWe didn't know how it would be\nWe were the dumb, the wild, the free\nLittle league\nAnd when we were younger\nWe wore our hearts right on our sleeves\nWhy did we ever have to leave?\nLittle league\n\nCould I get a rewind?\nGet another chance, take back in time\n'Cause I don't know what to do\nWith everything I'm going through\nAnd where did all my friends go?\nStanding on our street but nobody's home\nSwore we'd never move away\nBut now I'm going 95 on the interstate\n\n'Cause lately I've been feelin' strange\nAnd everybody's tellin' me to act my age\nI never thought that everything I had would fade away\n\nWhen we were younger\nWe didn't know how it would be\nWe were the dumb, the wild, the free\nLittle league\nAnd when we were younger\nWe wore our hearts right on our sleeves\nWhy did we ever have to leave?\nLittle league\n\nI wish I was younger\nOh, oh, oh, oh, oh\nWish I was younger\n\nWhen we were younger\nWe didn't know how it would be\nWe were the dumb, the wild, the free\nLittle league\n\nAnd when we were younger\nWe wore our hearts right on our sleeves\nWhy did we ever have to leave?\nLittle league",
        traduccion:"¿Recuerdas los días en nuestra vieja cuadra?\nMetiéndonos con nuestros vecinos que llamaron a la policía\nPodría jurar que tú y yo\nPodría salirse con la suya\nNos tumbábamos en la hierba todo el día hablando\nPorque nos escabullimos de la clase cuando nadie estaba mirando\nRecuerdo que tú y yo\nSí, recuerdo todo\n\nPero últimamente me he sentido extraña\nY todo el mundo me dice que actúe según mi edad\nNunca pensé que todo lo que tenía se desvanecería\n\nCuando éramos más jóvenes\nNo sabíamos cómo sería\nÉramos los tontos, los salvajes, los libres\nPequeña liga\nY cuando éramos más jóvenes\nLlevábamos nuestros corazones orgullosos en la manga\n¿Por qué tuvimos que irnos?\nLa pequeña liga\n\n¿Podría rebobinar?\nTendrás otra oportunidad de volver atrás en el tiempo\nPorque no sé qué hacer\nCon todo lo que estoy pasando\n¿Y adónde fueron todos mis amigos?\nEstán en mi calle, pero no hay nadie en casa\nJuró que nunca nos mudaríamos\nPero ahora voy a 95 en la interestatal\n\nPorque últimamente me he sentido extraño\nY todo el mundo me dice que actúe según mi edad\nNunca pensé que todo lo que tenía se desvanecería\n\nCuando éramos más jóvenes\nNo sabíamos cómo sería\nÉramos los tontos, los salvajes, los libres\nPequeña liga\nY cuando éramos más jóvenes\nLlevábamos nuestros corazones orgullosos en la manga\n¿Por qué tuvimos que irnos?\nLa pequeña liga\n\nDesearía que fuéramos jóvenes\nOh, tan joven\n\nCuando éramos más jóvenes\nNo sabíamos cómo sería\nÉramos los tontos, los salvajes, los libres\nPequeña liga\nY cuando éramos más jóvenes\nLlevábamos nuestros corazones orgullosos en la manga\n¿Por qué tuvimos que irnos?\nLa pequeña liga",
        video:"https://www.youtube.com/embed/pmZTq7frkDQ?si=Ka2iNT1S-6tA-TmE",
        reproductor:"/Audios/LittleLeague.mp3"
    },
    TheStory:{
        tittle:"The Story",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"Let me tell you a story\nAbout a boy and a girl\nIt’s kinda short, kinda boring\nBut the end is a whirl\nThey were just 16\nWhen the people were mean\nSo they didn’t love themselves\nAnd now they’re gone\nHeadstones on a lawn\n\nAnd when I was younger\nI knew a boy and a boy\nBest friends with each other\n(But always wished they were more)\n‘Cause they loved one another\nBut never discovered, ‘cause they were too afraid\nOf what they’d say\nMoved to different states\n\nOh, and I’m afraid that’s just the way the world works\nIt ain’t funny, it ain’t pretty, it ain’t sweet\nOh, and I’m afraid that’s just the way the world works\nBut I think that it could work for you and me\nJust wait and see\nIt’s not the end of the story\n\nNow it's onto the sequel\nAbout me and my friend\nBoth our parents were evil\nSo we both made a bet\nIf we worked and we saved\nWe could both run away\nAnd we’d have a better life\nAnd I was right\n(I wonder if she’s alright)\n\nOh, and I’m afraid that’s just the way the world works\nIt ain’t funny, it ain’t pretty, it ain’t sweet\nOh, and I’m afraid that’s just the way the world works\nBut I think that it could work for you and me\nJust wait and see\nIt’s not the end of the story\n\n(Okay)\n\nAnd all movie’s always running in my head\nAll the people, all the lovers, all my friends\nAnd I hope that they’ll all get their happy end\nIn the end\n\nOh, and I’m afraid that’s just the way the world works\nIt ain’t funny, it ain’t pretty, it ain’t sweet\nOh, and I’m afraid that’s just the way the world works\nBut I think that it could work for you and me\nJust wait and see\nIt’s not the end of the story",
        traduccion:"Dejame contarte una historia\nSobre un niño y una niña\nEs un poco corta, un poco aburrida\nPero el final es un torbellino\nSolo tenían 16\nCuando la gente era mala\nEntonces no se amaban a sí mismos\nY ahora se han ido\nLápidas en el césped\n\nY cuando era más joven\nConocí un niño y un niño\nMejores amigos entre ellos\n(Pero siempre desearon ser más)\nPorque se amaban\nPero nunca lo descubrieron, porque tenían demasiado miedo\nDe lo que dirían\nSe mudaron a diferentes estados\n\nOh, y me temo que así es como funciona el mundo\nNo es gracioso, no es lindo, no es dulce\nOh, y me temo que así es como funciona el mundo\nPero creo que podría funcionar para ti y para mí\nSolo espera y mira\nNo es el final de la historia\n\nAhora toca la secuela\nSobre mi y mi amiga\nNuestros padres eran malvados\nEntonces ambos hicimos una apuesta\nSi trabajábamos y ahorrábamos\nAmbos podríamos huir\nY tendríamos una vida mejor\nY yo tenía razón\n(Me pregunto si ella está bien)\n\nOh, y me temo que así es como funciona el mundo\nNo es gracioso, no es lindo, no es dulce\nOh, y me temo que así es como funciona el mundo\nPero creo que podría funcionar para ti y para mí\nSolo espera y mira\nNo es el final de la historia\n\n(Bueno)\n\nY todas las películas siempre están corriendo en mi cabeza\nToda la gente, todos los amantes, todos mis amigos\nY espero que tengan un final feliz\nAl final\n\nOh, y me temo que así es como funciona el mundo\nNo es gracioso, no es lindo, no es dulce\nOh, y me temo que así es como funciona el mundo\nPero creo que podría funcionar para ti y para mí\nSolo espera y mira\nNo es el final de la historia",
        video:"https://www.youtube.com/embed/Av4lI6ANeHY?si=-kIgJJPPuVx0X6KV",
        reproductor:"/Audios/thestory.mp3"
    },
    BedRest:{
        tittle:"Bed Rest",
        textColor: "rgb(19, 120, 235)",
        back:"Songs.html?album=KidKrow",
        fondo:"/Images/BedRest.webp",
        letra:"You know there’s a lot of things\nThat I wish that I didn’t do\nYou know there’s a side of me\nThat I wish that you never knew\n\nAnd although I'm crazy maybe just this time\nYou could try to see my sweeter side\nI promise after a little while longer\nI’ll come back to my senses\nBut now I need some bed rest\n\nLies filling up the room\nI honestly can’t tell what’s fake or true\nI run miles and miles from you\nI'm too afraid of what we’re gonna do\n\nAnd although I'm crazy maybe just this time\nOh, you could try to see our sweeter side\nI promise after a little while longer\nI’ll come back to my senses\nBut now I need some bed rest\n\nBut now I need some bed rest\nTo mend from all our trainwrecks\nOur love was all too reckless\nBut now I need some bed rest\nForget your name and address\nWe almost ended up dead\n\nDon’t look at me that way\nYou know we both did things to be ashamed\nI hope once our bruises fade\nWe’ll forget the things we did to us those days\nBut honestly, I’ll never be the same",
        traduccion:"Sabes que hay muchas cosas\nQue deseo ojalá no haberlas hecho\nSabes que hay un lado de mí\nQue ojalá nunca lo descubras\n\nY aunque estoy loco quizás solo esta vez\nPodrías intentar ver mi lado más dulce\nPrometo que después de un tiempo más\nVolveré a mis sentidos\nPero ahora necesito descansar un poco en cama\n\nMentiras llenando la habitación\nHonestamente no puedo distinguir qué es falso o verdadero\nCorro millas y millas de ti\nTengo demasiado miedo de lo que vayamos a hacer\n\nY aunque estoy loco quizás solo esta vez\nOh, podrías intentar ver mi lado más dulce\nPrometo que después de un tiempo más\nVolveré a mis sentidos\nPero ahora necesito descansar un poco en cama\n\nPero ahora necesito descansar un poco en cama\nPara recuperarnos de todos nuestros desastres\nNuestro amor fue demasiado egoísta\nPero ahora necesito descansar un poco en cama\nOlvidar tu nombre y dirección\nCasi terminamos muertos\n\nNo me mires de ese modo\nSabes que ambos hicimos cosas de las que avergonzarnos\nEspero que una vez que nuestros moretones desaparezcan\nOlvidaremos las cosas que nos hicieron aquellos días\nPero honestamente, nunca seré el mismo",
        video:"https://www.youtube.com/embed/-zoIL0n_9Vw?si=UivFFYzzaTWpkTpY",
        reproductor:"/Audios/Bed Rest.mp3"
    },
    Movies:{
        tittle:"Movies",
        textColor: "rgb(253, 76, 53)",
        back:"Songs.html?album=Superache",
        fondo:"/Images/Superache.jpg",
        letra:"Movies, movies\nI want a love like the movies\n\nI look at you like you're perfect for me\nIf you are the diamond, then I am the ring\nAll of our friends think of us jealously\nWe're so sweet, so sweet\n\nBuilt us a world and I gave you the key\nStill can't believe that this isn't a dream\nFalling in love with a damn fantasy\nThat's so me, so me\n\nBut I've been living\nLife in fiction\n\nIn my head\nWe're dancing in the dark\nIn my head\nWe kiss under the stars\nBut we know that's not what we're doing\n'Causе, baby, this ain't like the movies\n\nMoviеs, movies\nI want a love like the movies\n\nWe go to parties with people you know\nWe're holding hands, but it's all just for show\n'Cause Monday through Friday, we both barely spoke\nThey don't know, they can't know\n\nLike just on the drive here, I was looking through your texts\nI was screaming my damn head off how you still love your ex\nAnd you said that it's over, but why does she call you at 3AM and 4AM?\nThat's a funny way of staying friends\n\nIn my head\nWe're dancing in the dark\nIn my head\nWe kiss under the stars\nBut we know that's not what we're doing\n'Causе, baby, this ain't like the movies\n\nIn my head\nWe never grow apart\nIn my head\nYou never break my heart\nBut we know that's not what we're doing\n'Cause, baby, this ain't like the movies\n\nMovies, movies\nI want a love like the movies\nMovies, movies\nI want a love like the movies\n\nBaby, we lost all the love that we had (movies, movies)\nAnd I can't pretend it'll never come back (I want a love like the movies)\nAnd I think you're seeing right through me (movies, movies)\nBut, baby, this ain't like the movies\n\nAnd I want a love like the movies",
        traduccion:"Películas, películas\nQuiero un amor como en las películas\n\nTe miro y creo que eres perfecto para mí\nSi tú eres el diamante, yo soy el anillo\nTodos nuestros amigos nos miran con envidia\nSomos tan dulces, tan dulces\n\nCreamos un mundo y te di la llave\nAún no puedo creer que esto no sea un sueño\nEnamorándome de una maldita fantasía\nEso soy yo, eso soy yo\n\nPero he estado viviendo\nUna vida de ficción\n\nEn mi cabeza\nEstamos bailando en la oscuridad\nEn mi cabeza\nNos besamos bajo las estrellas\nPero sabemos que eso no es lo que estamos haciendo\nPorque, cariño, esto no es como en las películas\n\nPelículas, películas\nQuiero un amor como en las películas\n\nVamos a fiestas con gente que conoces\nNos tomamos de la mano, pero todo es solo para mostrar\nPorque de lunes a viernes apenas hablamos\nEllos no saben, no pueden saber\n\nComo cuando venía para acá, revisé tus mensajes\nEstaba gritando de frustración cómo todavía amas a tu ex\nY dijiste que ya terminó, pero, ¿por qué ella te llama a las 3 y 4 de la mañana?\nEs una forma curiosa de seguir siendo amigos\n\nEn mi cabeza\nEstamos bailando en la oscuridad\nEn mi cabeza\nNos besamos bajo las estrellas\nPero sabemos que eso no es lo que estamos haciendo\nPorque, cariño, esto no es como en las películas\n\nEn mi cabeza\nNunca nos alejamos\nEn mi cabeza\nNunca rompes mi corazón\nPero sabemos que eso no es lo que estamos haciendo\nPorque, cariño, esto no es como las películas\n\nPelículas, películas\nQuiero un amor como en las películas\nPelículas, películas\nQuiero un amor como en las películas\n\nCariño, hemos perdido todo el amor que teníamos (películas, películas)\nY no puedo pretender que nunca volverá (quiero un amor como en las películas)\nY creo que estás viendo a través de mí (películas, películas)\nPero, cariño, esto no es como en las películas\n\nY quiero un amor como en las películas",
        video:"https://www.youtube.com/embed/r4N6V8w5rNs?si=EsJlLdK9T7g5zrW9",
        reproductor:"/Audios/Movies.mp3"
    },
}

 /*   :{
        tittle:"",
        textColor: "rgb(253, 76, 53)",
        back:"Songs.html?album=Superache",
        fondo:"/Images/Superache.jpg",
        letra:"",\n
        traduccion:"",\n
        video:"",
        reproductor:"/Audios/.mp3"
    },
      */  

function obtenerParametro(nombre){
    const params = new
    URLSearchParams(window.location.search);
    return params.get(nombre)
}

const songKey = obtenerParametro("Song");
//tema
if(list[songKey]){
    document.documentElement.style.setProperty("--colorTexto",list[songKey].textColor);
}
if(list[songKey]){
    document.documentElement.style.setProperty("--fondo", `url(${list[songKey].fondo})`);
}


//back
if (list[songKey]){
    document.getElementById("back").href = list[songKey].back}


//titulo
if (list[songKey]){
    document.getElementById("tittle").innerText = list[songKey].tittle}
    

//letra
if (list[songKey]){
        document.getElementById("letra").innerText = list[songKey].letra}

//traduccion
if (list[songKey]){
    document.getElementById("traduccion").innerText = list[songKey].traduccion}

//video
if (list[songKey]){
    document.getElementById("video").src = list[songKey].video}

//audio
if (list[songKey]){
    const audio = document.getElementById("audios");
    audio.src = list[songKey].reproductor
    audio.load();
}



